---
# tasks file for kernel_headers (CentOS specific)

- name: Install kernel headers
  yum: name=kernel-devel state=present
  tags: kernel_headers
  when: not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))

# inside containers (mostly testing), kernel is imposed by host. headers might be or not be aligned.
- name: Install kernel headers - ignore errors if containers
  yum: name=kernel-devel state=present
  tags: kernel_headers
  ignore_errors: true
  when: (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))
